---
title: "Integrate PBMCs using Harmony"
format: html
---
  
# Integrating PBMC datasets from 10X

```{r init}
library(harmony)
library(Seurat)
library(ggplot2)
library(Azimuth)
library(patchwork)
```

Create Seurat object.

```{r seurat_object}
pbmc3k_mat <- Seurat::Read10X("../data/pbmc3k/filtered_gene_bc_matrices/hg19/")
pbmc8k_mat <- Seurat::Read10X("../data/pbmc8k/filtered_gene_bc_matrices/GRCh38/")

colnames(pbmc3k_mat) <- paste0('pbmc3k_', colnames(pbmc3k_mat))
colnames(pbmc8k_mat) <- paste0('pbmc8k_', colnames(pbmc8k_mat))

common_genes <- intersect(rownames(pbmc3k_mat), rownames(pbmc8k_mat))
pbmc3k_mat <- pbmc3k_mat[common_genes, ]
pbmc8k_mat <- pbmc8k_mat[common_genes, ]

seurat_obj <- CreateSeuratObject(
  counts = cbind(pbmc3k_mat, pbmc8k_mat),
  project = "PBMC",
  min.cells = 5
)

seurat_obj@meta.data$dataset <- c(
  rep("pbmc3k", ncol(pbmc3k_mat)),
  rep("pbmc8k", ncol(pbmc8k_mat))
)
```

Annotate.

```{r run_azimuth}
seurat_obj <- RunAzimuth(seurat_obj, reference = "pbmcref")
```


```{r}
seurat_obj_no_int <- SCTransform(seurat_obj) |>
  RunPCA(npcs = 20, verbose = FALSE) |>
  RunUMAP(dims = 1:20)

DimPlot(seurat_obj_no_int, reduction = "umap", group.by = "dataset", pt.size = .1) + ggtitle("Without harmony")
```

```{r}
seurat_obj_harmony <- SCTransform(seurat_obj) |>
  RunPCA(npcs = 20, verbose = FALSE) |>
  RunHarmony("dataset") |>
  RunUMAP(reduction = "harmony",  dims = 1:20)

DimPlot(seurat_obj_harmony, reduction = "umap", group.by = "dataset", pt.size = .1) + ggtitle("With harmony")
```

```{r}
DimPlot(seurat_obj_harmony, reduction = "umap", group.by = "predicted.celltype.l1", pt.size = .1) + ggtitle("With harmony")
```

Remove B cells from pbmc3k dataset and integrate.

```{r fig.width=8, fig.height=4}
pbmc3k_b_cells <- seurat_obj@meta.data[, "predicted.celltype.l1"] == "B" & seurat_obj@meta.data[, "dataset"]  == "pbmc3k"
seurat_obj_subset <- seurat_obj[, !pbmc3k_b_cells] |>
  SCTransform() |>
  RunPCA(npcs = 20, verbose = FALSE) |>
  RunHarmony("dataset") |>
  RunUMAP(reduction = "harmony",  dims = 1:20)

p1 <- DimPlot(seurat_obj_subset, reduction = "umap", group.by = "dataset", pt.size = .1) + ggtitle("No B cells")
p2 <- DimPlot(seurat_obj_subset, reduction = "umap", group.by = "predicted.celltype.l1", pt.size = .1) + ggtitle("No B cells")

p1 + p2
```

# Session Info

```{r}
sessionInfo()
```
